config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about_us", to: "about_us#index"
  get "services", to: "services#index"
  scope "/services" do
    get "dog_spa", to: "dog_spa#index"
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable
end

app/controllers/about_us_controller.rb
# frozen_string_literal: true

class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/dog_spa_controller.rb
# frozen_string_literal: true

class DogSpaController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/about_us/_locations.html.erb
<section class="body-font">
  <div class="container px-5 py-24 mx-auto">
  <h1 class="title-font text-xl md:text-3xl mb-4 font-medium text-default-brown">Conheça nossas unidades</h1>
    <div class="flex flex-wrap -mx-4 -mb-10 mt-10 text-center justify-center gap-10">
      <div class="w-[30.25rem] mb-10 px-4">
        <div class="rounded-lg overflow-hidden">
          <%= image_tag "MoradaFirstLocation.jpg", class:"object-cover object-center h-full w-full" %>
        </div>
        <p class="leading-relaxed text-base mt-5">Rua Holanda, n° 125, Horizonte - AM</p>
        <button class="mt-5 px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-background-brown rounded-[6px] hover:bg-opacity-90 focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80">
            Ver no mapa
        </button>
      </div>
      <div class="w-[30.25rem] mb-10 px-4">
        <div class="rounded-lg overflow-hidden">
          <%= image_tag "MoradaSecondLocation.jpg", class:"object-cover object-center h-full w-full" %>
        </div>
        <p class="leading-relaxed text-base mt-5">Av. Flores, n° 86, São Bernardo - AM</p>
        <button class="mt-5 px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-background-brown rounded-[6px] hover:bg-opacity-90 focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80">
            Ver no mapa
        </button>
      </div>
    </div>
  </div>
</section>

app/views/about_us/_mission_vision_values.html.erb
<section class="bg-background-brown">
    <div class="container px-6 py-12 mx-auto">
        <div class="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3 text-center">
            <div data-aos="fade-up">
                <%= image_tag "MissionVector.svg", class:"w-10 h-10 mx-auto my-5" %>

                <h1 class="mt-4 text-xl font-semibold text-white my-5">Missão</h1>

                <p class="mt-2 text-white">Oferecer conforto e diversão aos pets, garantindo qualidade nos serviços.</p>
            </div>

            <div data-aos="fade-up">
                <%= image_tag "VisionVector.svg", class:"w-10 h-10 mx-auto my-5" %>

                <h1 class="mt-4 text-xl font-semibold text-white my-5">Visão</h1>

                <p class="mt-2 text-white">Amor e respeito aos animais, segurança, profissionalismo e companheirismo.</p>
            </div>

            <div data-aos="fade-up">
                <%= image_tag "ValueVector.svg", class:"w-10 h-10 mx-auto my-5" %>

                <h1 class="mt-4 text-xl font-semibold text-white my-5">Valores</h1>

                <p class="mt-2 text-white">Ser referência em hotel para pets, proporcionando experiências positivas e duradouras para nossos clientes (pets e seus tutores).</p>
            </div>
        </div>
    </div>
</section>

app/views/about_us/_our_history.html.erb
<section class="text-default-brown body-font">
  <div class="container mx-auto md:mr-0 flex px-5 md:pl-5 md:pr-0 py-24 md:flex-row flex-col items-center">
    <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start text-left mb-16 md:mb-0 items-center">
      <h1 class="title-font text-xl md:text-3xl mb-4 font-medium text-default-brown w-full">Nossa história</h1>
      <br>
      <p class="mb-8 leading-relaxed">
        A Morada dos Pets nasceu em 2017 por dois apaixonados por pets que notaram a ausência de serviços como hospedagem para cães na cidade de Manaus.<br><br>
        Foi isso que nos inspirou a criar um hotel que oferecesse uma experiência positiva para os cãeszinhos, com muito carinho, companhia, entretenimento, além de colaborar com o seu desenvolvimento sensorial através de atividades. Criando assim, uma alternativa para auxiliar os tutores, que possuem rotinas corridas, a oferecer mais atenção aos seus filhos caninos.<br><br>
        Com duas unidades em Manaus (AM) a equipe Morada dos Pets é composta por 25 funcionários, todos compartilhando a mesma paixão pelos animais. Hoje, somos um dos principais hotéis de pets da região, cada vez mais buscamos expandir e aprimorar nossos serviços para continuar proporcionando confiança de que seus filhotes estarão em boas mãos e passarão dias incríveis por aqui!<br><br>
        Aos novos visitantes, esperamos vê-lo em breve na Morada dos Pets
      </p>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <%= image_tag "OurHistory.png", class:"object-cover object-center rounded-r-[10.5px] lg:rounded-r-none" %>
    </div>
  </div>
</section>

app/views/about_us/_testimonials_carousel.html.erb
<div class="relative" id="testimonialsCarousel">
  <h1 class="title-font text-xl md:text-3xl lg:ml-40 lg:text-left md:text-center pt-12 font-medium text-white px-5">Veja o que os nossos clientes têm a dizer</h1>

  <div class="swiper testimonials">
    <div class="swiper-wrapper">
      <div class="swiper-slide">
        <div class="container px-6 md:py-10 mx-auto h-full">
          <div class="lg:-mx-6 lg:flex lg:items-center justify-center h-full">
            <%= image_tag "FirstDogTestimonial.jpeg", class: "hidden lg:block object-cover object-center lg:w-[29.563rem] lg:mx-6 w-full lg:h-64 h-96 rounded-2xl" %>

            <div class="mt-8 lg:px-6 md:mt-0">
              <div class="max-w-lg text-white m-auto md:mx-auto">
                <div class="text-7xl lg:text-8xl font-normal text-white/25 -mb-8">“</div>
                <p>
                  Eu deixei meu cãozinho no hotel e fiquei muito satisfeita com o serviço prestado. Os funcionários foram super atenciosos e meu cachorro se divertiu muito durante todo o dia. Foi ótimo poder ter essa opção para cuidar do meu pet enquanto eu estava no trabalho. Recomendo!
                </p>
                <div class="text-7xl lg:text-8xl font-normal text-white/25 text-right -mb-8">”</div>
              </div>
              <p class="hidden lg:block text-white">- Cley Celeste</p>
              <div class="block lg:hidden flex items-center md:ml-24">
                 <%= image_tag "FirstDogTestimonial.jpeg", class: "object-cover object-center ring-4 ring-white w-14 h-14 rounded-full" %>

                <div class="mx-3">
                  <h1 class="font-semibold text-white">Cley Celeste</h1>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
    </div>

    <div class="swiper-pagination"></div>
    <div class="hidden md:block">
      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>
    </div>
  </div>
</div>

app/views/about_us/index.html.erb
<%= render(BannerComponent.new(
    image_reference: "aboutUs",
    title: "Quem somos?",
    description: "Como tudo começou..."
)) %>

<%= render "our_history" %>

<%= render "mission_vision_values" %>

<%= render "locations" %>

<%= render "testimonials_carousel" %>

<%= render "shared/footer" %>

app/views/dog_spa/index.html.erb
<%= render(BannerComponent.new(
    image_reference: "dogSpaService",
    title: "Dog Spa",
    description: "Um ambiente tranquilo e aconchegante"
)) %>

<section>
    <div class="container mx-auto md:mr-0 px-5 md:pl-5 md:pr-0 pt-24">
        <div class="lg:pr-24 md:pr-16 text-left mb-16 md:mb-0 w-full">
            <h1 class="title-font text-xl md:text-3xl mb-4 font-medium text-default-brown w-full">Seu cão precisa de um dia no spa?</h1>
            <br>
            <p class="mb-8 leading-relaxed">
                A Morada dos Pets possui um luxuoso Dog Spa, onde seu fiel companheiro pode desfrutar de momentos de puro relaxamento e mimos especiais.
            </p>
            <p class="mb-8 leading-relaxed">
            Oferecemos serviços como:
            </p>
        </div>
    </div>
</section>

<section class="body-font">
  <div class="container px-5 pb-24 mx-auto">
    <div class="flex flex-wrap -m-4">
      <div class="p-4 w-full sm:w-1/2 lg:w-1/3">
        <div class="h-full rounded-lg overflow-hidden shadow-price-cards">
          <%= image_tag "BathIcon.jpeg", class:"lg:h-48 md:h-36 w-full object-cover object-center rounded-b-lg" %>
          <div class="p-6">
            <h1 class="title-font text-lg font-medium text-black mb-3">Banho</h1>
            <p class="leading-relaxed mb-3 text-black">Limpeza dos ouvidos, shampoo, condicionador, toalha esterilizada</p>
            <div class="border-2 border-solid border-price-div"></div>
            <div class="py-3">
              <div class="space-y-2">
                <div class="flex items-center">
                  <span class="w-[5px] h-[5px] bg-black rounded-[10px] mr-2"></span>
                  <span>Pequeno porte</span> 
                  <span class="ml-auto font-semibold">R$: 44,90</span>
                </div>
                
                <div class="flex items-center">
                  <span class="w-[5px] h-[5px] bg-black rounded-full mr-2"></span>
                  <span>Médio porte</span> 
                  <span class="ml-auto font-semibold">R$: 54,90</span>
                </div>
                
                <div class="flex items-center">
                  <span class="w-[5px] h-[5px] bg-black rounded-full mr-2"></span>
                  <span>Grande porte</span> 
                  <span class="ml-auto font-semibold">R$: 64,90</span>
                </div>
              </div>
            </div>
            <p class="leading-relaxed text-black">Adicionais:</p>
            <div class="py-3">
              <div class="space-y-2">
                <div class="flex items-center">
                  <span class="w-[5px] h-[5px] bg-black rounded-[10px] mr-2"></span>
                  <span>Corte e lixamento de unhas</span> 
                  <span class="ml-auto font-semibold">R$: 14,90</span>
                </div>
                
                <div class="flex items-center">
                  <span class="w-[5px] h-[5px] bg-black rounded-full mr-2"></span>
                  <span>Escovação dos dentes</span> 
                  <span class="ml-auto font-semibold">R$: 9,99</span>
                </div>
              </div>
            </div>
            <div class="text-center">
              <button class="mt-12 px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-background-brown rounded-[6px] hover:bg-opacity-90 focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80">
                Solicitar
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="p-4 w-full sm:w-1/2 lg:w-1/3">
        <div class="h-full rounded-lg overflow-hidden shadow-price-cards">
          <%= image_tag "GroomingIcon.jpeg", class:"lg:h-48 md:h-36 w-full object-cover object-center rounded-b-lg" %>
          <div class="p-6">
            <h1 class="title-font text-lg font-medium text-black mb-3">Tosa</h1>
            <p class="leading-relaxed mb-3 text-black">Desde estilos tradicionais até cortes personalizados</p>
            <div class="border-2 border-solid border-price-div"></div>
          </div>
        </div>
      </div>
      <div class="p-4 w-full sm:w-1/2 lg:w-1/3">
        <div class="h-full rounded-lg overflow-hidden shadow-price-cards">
          <%= image_tag "MassageSessionIcon.jpeg", class:"lg:h-48 md:h-36 w-full object-cover object-center rounded-b-lg" %>
          <div class="p-6">
            <h1 class="title-font text-lg font-medium text-black mb-3">Sessão de massagem</h1>
            <p class="leading-relaxed mb-3 text-black">Auxilia no alívio do estresse e da tensão muscular</p>
            <div class="border-2 border-solid border-price-div"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_differentiators.html.erb
<section class="bg-background-white">
    <div class="container px-6 py-12 mx-auto">
        <div class="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
            <div class="flex flex-col items-center relative lg:border-r-2 lg:border-default-brown lg:pr-8" data-aos="fade-up">
                <%= image_tag "EmployeeVector.png", class:"w-76 h-76" %>
                <h1 class="mt-4 text-xl text-default-brown text-center">Equipe<br> especializada</h1>
            </div>

            <div class="flex flex-col items-center relative lg:border-r-2 lg:border-default-brown lg:pr-8" data-aos="fade-up">
                <%= image_tag "CameraVector.png", class:"w-76 h-76" %>
                <h1 class="mt-4 text-xl text-default-brown text-center">Segurança<br> 24 horas</h1>
            </div>

            <div class="flex flex-col items-center relative lg:border-r-2 lg:border-default-brown lg:pr-8" data-aos="fade-up">
                <%= image_tag "PetPawVector.png", class:"w-76 h-76" %>
                <h1 class="mt-4 text-xl text-default-brown text-center">Brinquedos<br> inspecionados</h1>
            </div>

            <div class="flex flex-col items-center relative" data-aos="fade-up">
                <%= image_tag "PetActivityVector.png", class:"w-76 h-76" %>
                <h1 class="mt-4 text-xl text-default-brown text-center">Ambiente<br> acolhedor</h1>
            </div>
        </div>
    </div>
</section>

app/views/home/_initial_presentation.html.erb
<section class="body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
      <video controls class="object-cover object-center rounded w-full h-full">
        <source src="https://videos.pexels.com/video-files/3023167/3023167-uhd_2560_1440_30fps.mp4" type="video/mp4" autoplay=true>
        Your browser does not support the video tag.
      </video>
    </div>
    <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start text-left items-center">
      <h1 class="title-font text-xl md:text-3xl mb-4 font-medium text-default-brown w-full">Com a Morada dos Pets, seu <br>melhor amigo sente-se em casa</h1>
      <p class="mb-8 leading-relaxed text-default-brown">Contamos com ambiente amplamente personalizado, para proporcionar experiências positivas aos nossos clientes.</p>
    </div>
  </div>
</section>

app/views/services/index.html.erb
<%= render(BannerComponent.new(
    image_reference: "services",
    title: "Conheça nossos serviços"
)) %>

<%= render "initial_services_presentation" %>

<%= render "shared/product_services_cards" %>

<%= render "services_steps" %>

<%= render "our_customers_carousel" %>

<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<footer class="bg-white mt-10">
    <div class="container p-6 mx-auto">
        <div class="lg:flex justify-center">
            <div class="w-full lg:w-2/5 text-center">
                <div class="px-6 py-6 mb-[50pt] md:py-0 md:mb-0">
                    <a href="/" class="w-auto h-7 inline-block">
                        <%= image_tag "Logo.png", class: "h-10 w-auto" %>
                    </a>

                    <p class="max-w-sm mt-5 mx-auto">Siga nas redes sociais</p>

                    <div class="flex justify-center mt-6 -mx-2">
                        <a href="https://www.instagram.com/" target="_blank" class="mx-2 text-gray-600 transition-colors duration-300 dark:text-gray-300 hover:text-blue-500 dark:hover:text-blue-400" aria-label="Instagram">
                            <%= image_tag "InstagramIcon.svg", class: "w-6 h-6 md:w-10 md:h-10 fill-current" %>
                        </a>

                        <a href="https://www.facebook.com/" target="_blank" class="mx-2 text-gray-600 transition-colors duration-300 dark:text-gray-300 hover:text-blue-500 dark:hover:text-blue-400" aria-label="Facebook">
                            <%= image_tag "FacebookIcon.svg", class: "w-6 h-6 md:w-10 md:h-10 fill-current" %>
                        </a>

                        <a href="https://www.tiktok.com/" target="_blank" class="mx-2 text-gray-600 transition-colors duration-300 dark:text-gray-300 hover:text-blue-500 dark:hover:text-blue-400" aria-label="TikTok">
                            <%= image_tag "TiktokIcon.svg", class: "w-6 h-6 md:w-10 md:h-10 fill-current" %>
                        </a>
                    </div>
                </div>
            </div>

            <div class="mt-6 lg:mt-0">
                <div class="grid grid-cols-2 gap-6 justify-center mx-auto md:w-96">
                    <div>
                        <h3 class="font-medium">Menu</h3>
                        <a href="/" class="block mt-2 font-normal">Início</a>
                        <a href="<%= about_us_path %>" class="block mt-2 font-normal">Quem somos</a>
                        <a href="<%= services_path %>" class="block mt-2 font-normal">Serviços</a>
                        <a href="#" class="block mt-2 font-normal">Contato</a>
                    </div>

                    <div>
                        <h3 class="font-medium">Endereços</h3>
                        <p class="block mt-2 font-normal">Rua Holanda, n° 125, Horizonte - AM</p>
                        <p href="#" class="block mt-2 font-normal">Av. Flores, n° 86, São Bernardo - AM</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-10">
            <p class="text-center">
                © Designed by <a href="https://www.linkedin.com/in/yamille-santos" target="_blank">Yamille Santos</a> 
                and developed by <a href="https://linkedin.com/in/yvescesar" target="_blank">Yves César</a>
            </p>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-white fixed w-full z-20 top-0 start-0 shadow" data-controller="mobile-menu">
    <div class="container mx-auto p-4 flex items-center justify-between">
        <a href="/" class="flex items-center">
            <%= image_tag "Logo.png", class: "h-10 w-auto sm:h-8 md:h-9" %>
        </a>

        <div id="menu-links" class="flex items-center space-x-10">
            <div class="hidden lg:flex items-center space-x-10">
                <a href="/" class="relative border-b-2 border-transparent transition-colors duration-300 transform mx-1.5 sm:mx-6 group">
                    Início
                    <span
                        class="absolute bottom-[-19.5pt] left-1/2 transform -translate-x-1/2 w-[108px] h-[6px] bg-background-brown rounded-full transition-transform duration-300 <%= current_page?(root_path) ? 'scale-x-100' : 'scale-x-0' %> group-hover:scale-x-100">
                    </span>
                </a>
                <a href="<%= about_us_path %>" class="relative border-b-2 border-transparent transition-colors duration-300 transform mx-1.5 sm:mx-6 group">
                    Quem somos
                    <span class="absolute bottom-[-19.5pt] left-1/2 transform -translate-x-1/2 w-[108px] h-[6px] bg-background-brown rounded-full transition-transform duration-300 <%= current_page?(about_us_path) ? 'scale-x-100' : 'scale-x-0' %> group-hover:scale-x-100"></span>
                </a>
                <a href="<%= services_path %>" class="relative border-b-2 border-transparent transition-colors duration-300 transform mx-1.5 sm:mx-6 group">
                    Serviços
                    <span class="absolute bottom-[-19.5pt] left-1/2 transform -translate-x-1/2 w-[108px] h-[6px] bg-background-brown rounded-full transition-transform duration-300 <%= current_page?(services_path) ? 'scale-x-100' : 'scale-x-0' %> group-hover:scale-x-100"></span>
                </a>
                <a href="#" class="relative border-b-2 border-transparent transition-colors duration-300 transform mx-1.5 sm:mx-6 group">
                    Contato
                    <span class="absolute bottom-[-19.5pt] left-1/2 transform -translate-x-1/2 w-[108px] h-[6px] bg-background-brown rounded-full transition-transform duration-300 group-hover:scale-x-100 scale-x-0"></span>
                </a>
            </div>

            <div id="auth-links" class="hidden lg:flex items-center space-x-4">
                <% if user_signed_in? %>
                    <%= button_to "Sair", destroy_user_session_path, method: :delete %>
                <% else %>
                    <%= link_to "Entrar", new_user_session_path, class: "px-6 py-2 font-medium tracking-wide box-border border tracking-wide capitalize transition-colors duration-300 transform bg-white border-background-brown rounded-[6px] hover:bg-background-brown hover:text-white focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80" %>
                    <%= link_to "Criar conta", new_user_registration_path, class: "px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-background-brown rounded-[6px] hover:bg-opacity-90 focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80" %>
                <% end %>
            </div>

            <div class="lg:hidden flex items-center">
                <button data-action="click->mobile-menu#toggle" data-mobile-menu-target="menuIcon" class="focus:outline-none">
                    <svg class="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>
    <div id="mobile-menu" class="hidden lg:hidden" data-mobile-menu-target="mobileMenu">
        <div class="p-4 space-y-6 mx-5">
            <a href="/" class="block">Início</a>
            <a href="<%= about_us_path %>" class="block">Quem somos</a>
            <a href="<%= services_path %>" class="block">Serviços</a>
            <a href="#" class="block">Contato</a>
            <% if user_signed_in? %>
                <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "block px-6 py-2 text-center font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-background-brown rounded-[6px] hover:bg-opacity-90 focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80" %>
            <% else %>
                <%= link_to "Entrar", new_user_session_path, class: "block px-6 py-2 text-center font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-background-brown rounded-[6px] hover:bg-opacity-90 focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80" %>
            <% end %>
        </div>
    </div>
</nav>

app/views/shared/_product_services_cards.html.erb
<section class="text-white body-font">
  <div class="w-full px-0 mx-auto">
    <div class="flex flex-wrap h-auto lg:h-[415.5pt]">
      <div class="w-full sm:w-1/2 lg:w-1/3">
        <div class="dogSpa h-full bg-gray-100 bg-opacity-75 px-8 pt-48 pb-24 flex flex-col justify-center items-center text-center relative group">
          <h1 class="title-font sm:text-2xl text-xl font-semibold text-white mb-3 transition-all duration-300 group-hover:mb-5 group-hover:mt-0 group-hover:translate-y-[-30px]">Dog Spa</h1>
          <div class="opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <p class="leading-relaxed mb-3 font-medium">Oferecemos tratamentos de spa personalizados, tosas profissionais e cuidados de alta qualidade para deixar seu cão relaxado.</p>
            <a href="<%= dog_spa_path %>">
              <button class="mt-12 px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-background-brown rounded-[6px] hover:bg-opacity-90 focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80">
                Saiba mais
              </button>
            </a>
          </div>
        </div>
      </div>
      <div class="w-full sm:w-1/2 lg:w-1/3">
        <div class="dogAccommodation h-full bg-gray-100 bg-opacity-75 px-8 pt-48 pb-24 flex flex-col justify-center items-center text-center relative group">
          <h1 class="title-font sm:text-2xl text-xl font-semibold text-white mb-3 transition-all duration-300 group-hover:mb-5 group-hover:mt-0 group-hover:translate-y-[-30px]">Hospedagem</h1>
          <div class="opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <p class="leading-relaxed mb-3 font-medium">Proporcionamos conforto, diversão, garantindo que seu amigo de quatro patas tenha uma estadia feliz e tranquila enquanto você estiver ausente.</p>
            <button class="mt-12 px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-background-brown rounded-[6px] hover:bg-opacity-90 focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80">
              Saiba mais
            </button>
          </div>
        </div>
      </div>
      <div class="w-full lg:w-1/3">
        <div class="dogTaxi h-full bg-gray-100 bg-opacity-75 px-8 pt-48 pb-24 flex flex-col justify-center items-center text-center relative group">
          <h1 class="title-font sm:text-2xl text-xl font-semibold text-white mb-3 transition-all duration-300 group-hover:mb-5 group-hover:mt-0 group-hover:translate-y-[-30px]">Dog Táxi</h1>
          <div class="opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <p class="leading-relaxed mb-3 font-medium h-[58.5pt]">Transporte seguro e confiável, garantindo viagens confortáveis.</p>
            <button class="mt-12 px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-background-brown rounded-[6px] hover:bg-opacity-90 focus:outline-none focus:ring focus:ring-background-brown focus:ring-opacity-80">
              Saiba mais
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>